version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: conshield-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo:7
    container_name: conshield-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
